### ISSUE TITLE
First example shows only Upgrade Required, not webpage.

### ISSUE THREAD

**Issue by martinerk0** [kinabalu/websocketsbook#1]
When on page http://localhost:8181 browser shows "Upgrade Required".
In console there is: Failed to load resource: the server responded with a status of 426 (Upgrade Required), and GET http://localhost:8181/ 426 (Upgrade Required).

**Comment by Collin512** [comment]
Hello, did you happen to figure out what the problem was? I am having the same issue. Super discouraging. I guess I can attempt to learn from another tutorial, but I just tossed the $20 at this and waited patiently for it to come in the mail.
I see these folks are mentioning a username and password that you can pass in the WebSocket object:
https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api
For the life of me I can't figure out what username and password this is referring to. I assume it's a username and password you set up on server.js?

**Comment by kinabalu** [comment]
@martinerk0 can you share any of your environment? have you followed the instructions perfectly?
