### ISSUE TITLE
Chapter One

### ISSUE THREAD

**Issue by ghost** [kinabalu/websocketsbook#2]
It is not made clear how to run the code. The only hint for running code is `node server.js` then it tells you to run the client.html. However as far as i can see there is no server running to serve the html file. What i did was split the two elements of code in ch1 and ch1html into two directories then run `node server.js` in one terminal and open a new terminal and fire up `http-server` (on :8081) which is a simple http server in node. This worked inasmuch as the socket wrote out to the terminal, not the console log.

Now i wouldn't expect console output to com from the the http running on port 8081 so i ran the console from 8181 the server.js. No console output and two error messages `Failed to load resource: the server responded with a status of 426 (Upgrade Required)` which i am still trying to work out as i have got the latest node and nam installed.

**Comment by kinabalu** [comment]
First thing to do is ensure you've run npm install in that directory.

You don't need to run an http-server, but it wouldn't hurt. The `client.html` will also work fine just opening it in the browser.

I would need more details to help here, are you sure the server is the only thing running on port 8181? It would appear that there might be another webserver listening in. By default the node ws library would send over the proper upgrade headers to make the connection with the client, and that isn't happening.

If you have error logs from the browser, and can zip up a copy of your `ch1/` directory I can help further

**Comment by Collin512** [comment]
Hi, I am having the same issue. I don't know if something has changed since you wrote the book, but I'm super bummed out because I got my book in from Amazon today, popped it open, tried the first example, and no dice! I am getting a 426 error as well.
I have tried to dive into learning what the problem is, and apparently it has to do with the request header. I see some folks on stackOverflow saying that you can put a username and password into the websocket object, and I just can't seem to understand what is going on. Do you know what username and password these folks may be talking about? Do I need to register somewhere to use the websocket API?
Thank you for your time. I have a feeling I will love the book once I can get rolling with it. I made a chat room, and had to use polling on it to get it to get data. It's just dumb. i want to rock the web sockets so bad I can taste it!

**Comment by Collin512** [comment]
Heads up, it works fine on my Mac, but did not work on my Windows machine. Don't know why this is.

**Comment by Collin512** [comment]
I found out what the problem is. It's because I was trying to navigate to the web page by typing localhost:8181/client.html, like I would when using something like MAMP. 
In this case the static HTML page is what is making the connection to the web socket, so you actually navigate to the file in your browser, like file:///Users/collin/Desktop/websocket/client.html. This is counterintuitive to me as a PHP developer, where the server is always on and defaults to index.html.
Of course, I am learning, so I may not make much sense, but I think that's the problem. You navigate to the client file path...and port 8181 is not serving anything until you do so. Is that correct? Am I at least kinda on the right track?

**Comment by kinabalu** [comment]
@Collin512 yes, you're on the right track. Given the simplicity of the connection, you don't explicitly have to enable an HTTP server as it's just HTML and JavaScript so it isn't required.  As mentioned above though, you could opt to run an http server by running
`npm install http-server` and running `http-server` where the client.html directory is and running that way.

Let me know if you have any trouble.

**Comment by Collin512** [comment]
Thank you. I got http-server installed, but now I'm having trouble finding the path to run the server on. I'm sure I'll get it, just need to research some more. Apparently there can be a naming conflict from what I understand.
Glad I'm at least kind of understanding what is going on with the server. HTTP is a deep subject, and I don't want to be ignorant about it, so I am studying what I can.
Thank you for the response. Loving the book.

**Comment by kinabalu** [comment]
If I were running this, I'd run the [http-server](https://www.npmjs.com/package/http-server) from wherever the html is so you could talk using `http://localhost:8181` or whatever [http-server](https://www.npmjs.com/package/http-server) says it is listening on.

Good luck!
